[package]
name = "combinatorica"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.82"
